name: Build & Deploy Tenant

on:
  push:
    branches: [ "main", "deploy/**" ] # dla każdego tenant PR

env:
  IMAGE_NAME: quiz_app_ct

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load tenant config
        run: |
          source ./envs/.env.${{ github.ref_name }} # np. .env.tenant123
          echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV
          echo "TENANT_ID=$TENANT_ID" >> $GITHUB_ENV

      - name: Build & Push Docker image
        run: |
          docker login ghcr.io -u keydyy -p ${{ secrets.GH_PAT }}
          docker build . \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_KEY} \
            --build-arg TENANT_ID=${TENANT_ID} \
            --tag ghcr.io/keydyy/${{ env.IMAGE_NAME }}-${TENANT_ID}:latest
          docker push ghcr.io/keydyy/${{ env.IMAGE_NAME }}-${TENANT_ID}:latest

      - name: Terraform deploy Azure Container App
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="tenant_id=${TENANT_ID}" \
            -var="image=ghcr.io/keydyy/${{ env.IMAGE_NAME }}-${TENANT_ID}:latest"
