name: Delete Tenant

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: 'Tenant ID to delete'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY_OWNER: keydyy

jobs:
  delete_tenant:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Tenant State
        id: get_state
        run: |
          # Get storage account connection string
          az storage account show-connection-string \
            --name quizappblobs \
            --resource-group quizapp \
            --query connectionString \
            --output tsv > connection_string.txt
          
          CONNECTION_STRING=$(cat connection_string.txt)
          
          # Download tenant state
          az storage blob download \
            --connection-string "$CONNECTION_STRING" \
            --container-name "tenant-states" \
            --name "${{ github.event.inputs.tenant_id }}/state.json" \
            --file tenant-state.json \
            --auth-mode key
          
          # Read tenant state
          TENANT_STATE=$(cat tenant-state.json)
          echo "tenant_state=$TENANT_STATE" >> $GITHUB_OUTPUT

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=quizapp" \
            -backend-config="storage_account_name=quizapptfstate" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="use_oidc=true" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"

      - name: Terraform Plan
        run: |
          # Extract tenant info from state
          TENANT_ID="${{ github.event.inputs.tenant_id }}"
          TENANT_STATE="${{ steps.get_state.outputs.tenant_state }}"
          
          # Create a temporary tfvars file with empty container_apps
          cat > terraform.tfvars <<EOF
          github_repository = "keydyy/quiz_app_ct"
          ghcr_username = "keydyy"
          ghcr_pat = "${{ secrets.GH_PAT }}"
          create_new_environment = false
          image_name = "quiz_app_ct"
          container_apps = {}
          EOF
          
          # Plan the destruction
          terraform plan -var-file=terraform.tfvars -destroy -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Cleanup Tenant State
        run: |
          # Get storage account connection string
          CONNECTION_STRING=$(cat connection_string.txt)
          
          # Delete tenant state blob
          az storage blob delete \
            --connection-string "$CONNECTION_STRING" \
            --container-name "tenant-states" \
            --name "${{ github.event.inputs.tenant_id }}/state.json" \
            --auth-mode key
          
          # Delete tenant container
          az storage container delete \
            --connection-string "$CONNECTION_STRING" \
            --name "tenant-${{ github.event.inputs.tenant_id }}" \
            --auth-mode key

      - name: Delete Container Image
        run: |
          # Delete the container image from GHCR
          gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
          gh api \
            -X DELETE \
            "/user/packages/container/quiz_app_ct-${{ github.event.inputs.tenant_id }}/versions" \
            -f package_type=container \
            -f package_name="quiz_app_ct-${{ github.event.inputs.tenant_id }}"

      - name: Deployment Summary
        run: |
          echo "## Tenant Deletion Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Tenant ID | \`${{ github.event.inputs.tenant_id }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Deleted |" >> $GITHUB_STEP_SUMMARY
          echo "| Deleted Resources | Container App, Storage Container, Container Image, Tenant State |" >> $GITHUB_STEP_SUMMARY 