name: Delete Tenant

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: 'Tenant ID to delete'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY_OWNER: keydyy
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

jobs:
  delete_tenant:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Tenant State
        id: get_state
        run: |
          CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}"
          
          az storage blob download \
            --connection-string "$CONNECTION_STRING" \
            --container-name "tenant-states" \
            --name "${{ github.event.inputs.tenant_id }}/state.json" \
            --file tenant-state.json \
            --auth-mode key

          TENANT_STATE=$(cat tenant-state.json)
          echo "tenant_state=$TENANT_STATE" >> $GITHUB_OUTPUT

      - name: Verify Tenant Status
        run: |
          CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}"
          APP_STATUS=$(az containerapp show \
            --name "quiz-app-${{ github.event.inputs.tenant_id }}" \
            --resource-group quizapp \
            --query "properties.provisioningState" \
            --output tsv 2>/dev/null || echo "not_found")

          if [[ "$APP_STATUS" == "Running" ]]; then
            echo "Error: Tenant is currently running and cannot be deleted"
            exit 1
          fi

          BACKUP_TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
          az storage blob copy start \
            --connection-string "$CONNECTION_STRING" \
            --source-container "tenant-states" \
            --source-blob "${{ github.event.inputs.tenant_id }}/state.json" \
            --destination-container "tenant-states-backup" \
            --destination-blob "${{ github.event.inputs.tenant_id }}/state_${BACKUP_TIMESTAMP}.json" \
            --auth-mode key

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=quizapp" \
            -backend-config="storage_account_name=quizapptfstate" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=quiz-app/tenant-${{ github.event.inputs.tenant_id }}/terraform.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Plan
        run: |
          cat > terraform.tfvars <<EOF
          tenant_id = "${{ github.event.inputs.tenant_id }}"
          destroy_mode = true
          EOF

          terraform plan -var-file=terraform.tfvars -destroy -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Verify Resource Deletion
        run: |
          if az containerapp show \
            --name "quiz-app-${{ github.event.inputs.tenant_id }}" \
            --resource-group quizapp &>/dev/null; then
            echo "Error: Container app still exists"
            exit 1
          fi

          CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}"
          if az storage container show \
            --connection-string "$CONNECTION_STRING" \
            --name "tenant-${{ github.event.inputs.tenant_id }}" \
            --auth-mode key &>/dev/null; then
            echo "Error: Storage container still exists"
            exit 1
          fi

      - name: Cleanup Tenant State
        run: |
          CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}"
          az storage blob delete \
            --connection-string "$CONNECTION_STRING" \
            --container-name "tenant-states" \
            --name "${{ github.event.inputs.tenant_id }}/state.json" \
            --auth-mode key || echo "Warning: Failed to delete tenant state blob"

          az storage container delete \
            --connection-string "$CONNECTION_STRING" \
            --name "tenant-${{ github.event.inputs.tenant_id }}" \
            --auth-mode key || echo "Warning: Failed to delete tenant container"

      - name: Delete Container Image
        run: |
          gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

          PACKAGE_VERSIONS=$(gh api \
            -X GET "/user/packages/container/quiz_app_ct-${{ github.event.inputs.tenant_id }}/versions" \
            --jq '.[].id' || echo "")

          for version_id in $PACKAGE_VERSIONS; do
            gh api -X DELETE "/user/packages/container/quiz_app_ct-${{ github.event.inputs.tenant_id }}/versions/$version_id" || echo "Warning: Failed to delete version $version_id"
          done

      - name: Deployment Summary
        run: |
          echo "## Tenant Deletion Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Tenant ID | \`${{ github.event.inputs.tenant_id }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Deleted |" >> $GITHUB_STEP_SUMMARY
          echo "| Deleted Resources | Container App, Storage Container, Container Image, Tenant State |" >> $GITHUB_STEP_SUMMARY
          echo "| Backup Created | Yes (in tenant-states-backup container) |" >> $GITHUB_STEP_SUMMARY
          echo "| Verification | All resources verified as deleted |" >> $GITHUB_STEP_SUMMARY
